name: StargateCustomizations
version: ${project.version}
main: dev.thorinwasher.stargate.customizations.StargateCustomizations
description: An admin utility module for Stargate Rewritten providing wieldiness exceptions (mostly webGUIs and extra config files) 
authors: [ Thorinwasher, EpicKnarvik97 ]
website: https://sgrewitten.org/customizations
api-version: 1.20
dependencies:
  server:
    Stargate:
      load: BEFORE
      required: true
      join-classpath: true
    ColorBukkit:
      load: BEFORE
      required: false
      join-classpath: true
    StargateInterfaces:
      load: AFTER
      required: false
      join-classpath: true
