name: StargateExtraColors
main: dev.thorinwasher.extracolors.Stargate
version: @version@
description: Stargate mod for Bukkit
authors: [ Thorin ]
website: https://discord.gg/mTaHuK6BVa
api-version: 1.15
softdepend: [ ColorBukkit ]