name: StargateCustomizations
main: dev.thorinwasher.stargate.customizations.StargateCustomizations
version: @version@
description: A style and customization addon for stargate
authors: [ Thorin ]
website: https://discord.gg/mTaHuK6BVa
api-version: 1.15
softdepend: [ ColorBukkit ]
depend: [Stargate]
